export const BRIDGE_ACTIONS = {
  COPY_FILES: 'copyFiles',
  DELETE_FILES: 'deleteFiles',
  EXPORT_TAGS_CSV: 'exportTagsCsv',
  EXPORT_TAGS_JSON: 'exportTagsJson',
  EXPORT_TAGS_XMP: 'exportTagsXmp',
  FIND_DUPLICATES: 'findDuplicates',
  FLIP_IMAGES: 'flipImages',
  GET_ALL_TAGS: 'getAllTags',
  GET_DRIVES: 'getDrives',
  GET_FOLDER_CONTENTS: 'getFolderContents',
  GET_FOLDERS: 'getFolders',
  GET_FULL_IMAGE: 'getFullImage',
  GET_IMAGES: 'getImages',
  GET_PROPERTIES: 'getProperties',
  GET_RATING: 'getRating',
  GET_TAG_LIBRARY: 'getTagLibrary',
  GET_THUMBNAIL: 'getThumbnail',
  GET_THUMBNAILS_BATCH: 'getThumbnailsBatch',
  HEALTH_CHECK: 'healthCheck',
  IMPORT_TAGS_CSV: 'importTagsCsv',
  IMPORT_TAGS_JSON: 'importTagsJson',
  MOVE_FILES: 'moveFiles',
  OPEN_IN_EXPLORER: 'openInExplorer',
  READ_TAGS: 'readTags',
  RENAME_FILE: 'renameFile',
  ROTATE_IMAGES: 'rotateImages',
  SAVE_TAG_LIBRARY: 'saveTagLibrary',
  SEARCH_IMAGES: 'searchImages',
  SELECT_FOLDER: 'selectFolder',
  SET_RATING: 'setRating',
  STOP_WATCHING: 'stopWatching',
  UPDATE_BATCH_TAG: 'updateBatchTag',
  WATCH_FOLDER: 'watchFolder',
  WRITE_BATCH_TAGS: 'writeBatchTags',
  WRITE_TAGS: 'writeTags',
} as const;

export type BridgeActionName = (typeof BRIDGE_ACTIONS)[keyof typeof BRIDGE_ACTIONS];
